name: CI-CD Pipeline

on:
  push:

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t myapp .

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Stop old container
        run: docker stop myapp || true

      - name: Remove old container
        run: docker rm myapp || true

      - name: Run container
        run: docker run -d -p 3000:3000 --name myapp myapp
